# Generated by Django 5.2.6 on 2026-09-04 09:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('YOUTUBE_ATTEMPT_FOCUS', 'YouTube Blocked During Focus 🔒'), ('SHORTS_BLOCKED_BREAK', 'Shorts Intercepted During Break ❌'), ('APP_BLOCKED_FOCUS', 'Protected App Blocked 🚫'), ('BREAK_OVERRUN', 'Break Overrun ⚠️'), ('LONG_VIDEO_WATCHED', 'Long Video Watched ✅'), ('BREAK_COMPLETED', 'Break Completed On Time 🌿')], max_length=40)),
                ('app_name', models.CharField(default='YouTube', max_length=60)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CuratedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=120)),
                ('duration_str', models.CharField(default='24m', max_length=20)),
                ('duration_minutes', models.IntegerField(default=24)),
                ('youtube_id', models.CharField(max_length=60)),
                ('category', models.CharField(default='Documentary', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('watch_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_saved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FocusState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('FOCUS', 'Focus Mode 🔒'), ('BREAK', 'Break Mode 🌿'), ('IDLE', 'Idle ⏸️')], default='FOCUS', max_length=20)),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=64)),
                ('task_name', models.CharField(default='Deep Work / Study', max_length=120)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('planned_duration_minutes', models.IntegerField(default=50)),
                ('next_break_time', models.DateTimeField(blank=True, null=True)),
                ('active_video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('active_video_title', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Focus State',
                'verbose_name_plural': 'Focus State',
            },
        ),
        migrations.CreateModel(
            name='ProtectedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('special_rule', models.CharField(default='Blocked during focus', max_length=150)),
                ('icon', models.CharField(default='shield', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('FOCUS', 'Focus Session'), ('BREAK', 'Break Session')], max_length=20)),
                ('task_name', models.CharField(default='Session', max_length=120)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('planned_duration_minutes', models.IntegerField(default=20)),
                ('actual_duration_minutes', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=True)),
                ('overrun', models.BooleanField(default=False)),
                ('overrun_minutes', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
