# Generated by Django 5.2.6 on 2026-09-07 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('handle', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('channel_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('custom_url', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('subscriber_count', models.CharField(blank=True, default='', max_length=50)),
                ('video_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='curatedvideo',
            name='channel_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.youtubechannel'),
        ),
    ]
