# Generated by Django 5.2.6 on 2026-09-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_youtubechannel_curatedvideo_channel_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusstate',
            name='email',
            field=models.EmailField(default='student@gmail.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='focusstate',
            name='mode',
            field=models.CharField(choices=[('FOCUS', 'Focus Mode 🔒'), ('BREAK', 'Break Mode 🌿'), ('IDLE', 'Idle ⏸️')], default='IDLE', max_length=20),
        ),
    ]
